# permissions for end users to edit runnerpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerpool-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - meows.cybozu.com
  resources:
  - runnerpools
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meows.cybozu.com
  resources:
  - runnerpools/status
  verbs:
  - get
