apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cybozu-go.github.io/moco
    chart: moco
    targetRevision: 0.1.2
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: moco-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
