apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./upstream/crd
  - ./upstream/controller
  - ./upstream/agent
  - ./upstream/runnerpool/runnerpool_editor_role.yaml
  - ./upstream/runnerpool/runnerpool_viewer_role.yaml
  - runnerpool.yaml
patchesStrategicMerge:
  - ./deployment.yaml
