apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system
resources:
  - upstream/crd
  - rbac
  - operator.yaml
  - vmagent.yaml
  - vmsingle.yaml
  - rules/argocd-scrape.yaml
  - rules/kubernetes-scrape.yaml

images:
- name: victoriametrics/operator
  newTag: v0.19.1
