apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system
resources:
  - upstream/default
  - vmagent.yaml
  - vmsingle.yaml

images:
- name: victoriametrics/operator
  newTag: v0.19.1
