
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-meows-cybozu-com-v1alpha1-runnerpool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: runnerpool-hook.meows.cybozu.com
  rules:
  - apiGroups:
    - meows.cybozu.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - runnerpools
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1alpha1
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-meows-cybozu-com-v1alpha1-runnerpool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: runnerpool-hook.meows.cybozu.com
  rules:
  - apiGroups:
    - meows.cybozu.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runnerpools
  sideEffects: None
