apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kubernetes
spec:
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabelConfigs:
      - replacement: kubernetes-apiservers
        targetLabel: job
  - port: https
    scheme: http
    relabelConfigs:
      - replacement: kube-controller-manager
        targetLabel: job
      - sourceLabels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:10252
        targetLabel: __address__
      - sourceLabels: [__address__]
        targetLabel: instance
  - port: https
    scheme: http
    relabelConfigs:
      - replacement: kube-scheduler
        targetLabel: job
      - sourceLabels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:10251
        targetLabel: __address__
      - sourceLabels: [__address__]
        targetLabel: instance
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-nodes
spec:
  scheme: https
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - replacement: kubernetes-nodes
      targetLabel: job
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-cadvisor
spec:
  scheme: https
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - replacement: kubernetes-cadvisor
      targetLabel: job
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
