apiVersion: v1
kind: ConfigMap
metadata:
  name: mcing-server-props
  namespace: minecraft
data:
  difficulty: normal
  motd: A Vanilla Minecraft Server powered by MCing
  pvp: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: other-props
  namespace: minecraft
data:
  banned-ips.json: |
    []
  banned-players.json: |
    []
  whitelist.json: |
    []
  ops.json: |
    []
---
apiVersion: mcing.kmdkuk.com/v1alpha1
kind: Minecraft
metadata:
  name: kmdkuk-minecraft
  namespace: minecraft
spec:
  podTemplate:
    spec:
      containers:
      - env:
        - name: TYPE
          value: SPIGOT
        - name: VERSION
          value: 1.16.3
        - name: EULA
          value: "true"
        image: itzg/minecraft-server:java8
        name: minecraft
  serverPropertiesConfigMapName: mcing-server-props
  otherConfigMapName: other-props
  serviceTemplate:
    metadata:
      annotations:
        "mc-router.itzg.me/externalServerName": "kmdkuk-minecraft.minecraft.kmdkuk.com"
    spec:
      type: NodePort
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
