apiVersion: v1
kind: ConfigMap
metadata:
  name: test-server-props
  namespace: minecraft
data:
  difficulty: normal
  motd: A Vanilla Minecraft Server powered by MCing
  pvp: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-other-props
  namespace: minecraft
data:
  banned-ips.json: |
    []
  banned-players.json: |
    []
  whitelist.json: |
    []
  ops.json: |
    [
      {
        "uuid": "0f6aabaf-471a-4ddc-b924-efb96a307dcd",
        "name": "kmdkuk",
        "level": 4,
        "bypassesPlayerLimit": false
      }
    ]
---
apiVersion: mcing.kmdkuk.com/v1alpha1
kind: Minecraft
metadata:
  name: test
  namespace: minecraft
spec:
  podTemplate:
    spec:
      containers:
      - env:
        - name: TYPE
          value: SPIGOT
        - name: VERSION
          value: 1.17.1
        - name: EULA
          value: "true"
        image: itzg/minecraft-server:latest
        name: minecraft
  serverPropertiesConfigMapName: test-server-props
  otherConfigMapName: test-other-props
  serviceTemplate:
    metadata:
      annotations:
        "mc-router.itzg.me/externalServerName": "test.minecraft.kmdkuk.com"
    spec:
      type: LoadBalancer
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard
