apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: victoriametrics
spec:
  name: victoriametrics.yaml
  datasources:
    - name: vmsingle
      type: prometheus
      access: proxy
      url: http://vmsingle-vmsingle.monitoring-system.svc:8429
      version: 1
      isDefault: false
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "30s"
