apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  service:
    type: NodePort
    ports:
      - name: http
        port: 80
        protocol: TCP
        nodePort: 30081
  config:
    log:
      level: "warn"
    auth:
      disable_login_form: false
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
