# cluster-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # for argocd-server
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  # for grafana
  - containerPort: 30081
    hostPort: 30081
    protocol: TCP
- role: worker
- role: worker
- role: worker
